apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-config
  namespace: kubecomp
data:
  resource-config.txt: |
    1,1
    2,1
    3,1
    4,1
    5,2
    6,2
    7,2
    8,2
    9,3
    10,3
    11,3
    12,3
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-pool-deployment
  namespace: kubecomp
  labels:
    app: resource-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-pool
  template:
    metadata:
      labels:
        app: resource-pool
    spec:
      containers:
      - name: resource-pool
        image: resource-pool
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: rp-svc
        volumeMounts:
        - name: "resource-config"
          mountPath: "/config"
          readOnly: true
        command: ['sh', '-c', '/bin/resource-pool /config/resource-config.txt']
      volumes:
        - name: "resource-config"
          configMap:
            name: resource-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: resource-pool-service
  namespace: kubecomp
spec:
  selector:
    app: resource-pool
  ports:
  - name: resource-pool
    protocol: TCP
    port: 8000
    targetPort: rp-svc
