apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  device-plugin-config.yaml: |
    api_endpoint: {{ .Values.configMap.api_endpoint }}
    local_ips: {{ .Values.configMap.local_ips }}
    host_ports: {{ .Values.configMap.host_ports }}
    